### ISSUE TITLE
Certificate for Website Not Updated

### ISSUE THREAD

**Issue by ems215** [sbidolach/mobile-gamepad#14]
Hi,

I am trying to update my Retro Game Engine that I got to play retro games. It gets to the point where it is updating the mobile-gamepad and it says the certificate is not updated for the site from which it is downloading.

Can anyone please help?

Thanks

**Comment by sbidolach** [comment]
It is difficult to say where is the issue but maybe there were some issues with the GitHub certificate. Retropie downloads this gamepad from Github directly.
