### ISSUE TITLE
Analog Input

### ISSUE THREAD

**Issue by punkr0csux** [sbidolach/mobile-gamepad#7]
Sorry if this is the wrong way to bring up issues:

I ran the commands to get input data from the Mobile Gamepad:
sudo apt-get install input-utils
sudo lsinput
sudo input-events [number]

When using the dpad i noticed that only 2 events show up before the analog stick stops responding:

//The X and Y values are dependent on the direction I  press to test the analog input

EV_ABS ABS_Y 127                       
EV_SYN code=0 value=0
EV_ABS ABS_X 255                      
EV_SYN code=0 value=0

I've tested this and received the same errors from from chrome on android and chrome from windows 10.

**Comment by sbidolach** [comment]
Did you test this on Raspberry Pi or another device?

**Comment by punkr0csux** [comment]
It's on  Raspberry Pi 3 using Retropie. I installed the drivers from the experimental driver menu of the RetroPie setup.
